version: "3.7"

services:
  webserver:
    container_name: webserver
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    command: "python3 -m flask run --debug --host=0.0.0.0"
    volumes:
      - ".:/home/jovyan"
    environment:
      - FLASK_APP=webserver.app
      - FLASK_ENV=development
      - WALLS_DETECTION_MODEL_FILE=/tmp/models/model_6_566.00565.pt
  notebook:
    container_name: notebook
    build:
      context: .
      dockerfile: ./Dockerfile
    shm_size: 32gb
    ports:
      - 8888:8888
    command: "start-notebook.py --IdentityProvider.token=''"
    volumes:
      - ".:/home/jovyan"
    environment:
      - WALLS_DETECTION_MODEL_FILE=/tmp/models/model_6_566.00565.pt
